import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/registry";
import "./globals.css";
import { SharedProvider } from "./contexts/SharedContext";
import { Toaster } from "react-hot-toast";
import { Vazirmatn } from "next/font/google";

const vazir = Vazirmatn({ subsets: ["arabic"], variable: "--font-vazir" });

export const metadata: Metadata = {
  title: "سایت ساز تومک",
  description: "Generated by Toomak",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`  ${vazir.variable}`}>
        <Toaster position="top-center" containerClassName="text-right" />
        <SharedProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </SharedProvider>
      </body>
    </html>
  );
}
