import type { Metadata } from "next";
import { Cairo } from "next/font/google";

import StyledComponentsRegistry from "@/lib/registry";
import "./globals.css";

const cairoFont = Cairo({
  weight: "400",
  subsets: ["arabic"],
  variable: "--font-cairo",
});


export const metadata: Metadata = {
  title: "سایت ساز تومک",
  description: "Generated by Toomak",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cairoFont.variable}  antialiased`}
      >
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
